controller_list:
  - name: fake_arm_controller_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses per group
  - group: arm_controller
    pose: zero_pose