arm_controller_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
  gains:
    joint1:
      p: 20
      d: 0.01
      i: 0.25
      i_clamp: 1
    joint2:
      p: 20
      d: 0.0
      i: 0.25
      i_clamp: 1
    joint3:
      p: 20
      d: 0.0
      i: 0.25
      i_clamp: 1
    joint4:
      p: 20
      d: 0.0
      i: 0.1
      i_clamp: 1
    joint5:
      p: 20
      d: 0.0
      i: 0.1
      i_clamp: 1